utils::globalVariables(c("num", "year", "runif", "error", "na_prop", "sd_error", "max_dev", "count", "ratio",
                         "ex_denominator", "ex_numerator", ".", "dev_temp", "num_next", "numerator_include",
                         "denominator_include", "ata_ratio", "any_valid_ratio", "max_ratio", "min_ratio",
                         "valid_group", "high_flag", "low_flag", "max_high_row", "max_low_row",
                         "denominator_count", "numerator_count", "numerator", "denominator", "ata",
                         "atu", "pct_dev", "original_data_flag", "ata_fit", "dev_period", "x_t", "y_t",
                         "ata_count", "xx", "x", "n", "xy", "y", "yy", "sxy", "sxx", "b", "syy", "a",
                         "weibull_r_squared", "exponential_r_squared", "x_t_1", "x_t_2", "x_t_3", "x_t_4",
                         "x_t_5", "xx_1", "x_1", "xx_2", "x_2", "xx_3", "x_3", "xx_4", "x_4", "xx_5", "x_5",
                         "xy_1", "xy_2", "xy_3", "xy_4", "xy_5", "sxx_1", "sxy_1", "sxy_2", "sxx_2",
                         "sxy_3", "sxx_3", "sxy_4", "sxx_4", "sxy_5", "sxx_5", "r_squared_1",
                         "r_squared_2", "r_squared_3", "r_squared_4", "r_squared_5",
                         "b_1", "b_2", "b_3", "b_4", "b_5", "max_r_squared", "inv_power_r_squared",
                         "selected_c", "selected_curve_ata", "selected_ata", "weibull_ata",
                         "exponential_ata", "inv_power_ata", "row_num", "lambda", "lr_numerator",
                         "lr_denominator", "cc_lr", "ultimate", "dev_month", "dof", "sigma",
                         "extrapolated_sigma1", "extrapolated_sigma2", "extrapolated_sigma3",
                         "extrapolated_sigma", "projected_values", "cohort", "reserve", "mack_se", "%>%",
                         "row_number", "total_rows", "incr_actual", "incr_expected", "expected_amount",
                         "actual_ibnr", "expected_ibnr", "ave", "change_in_ibnr", "diag_num", "cdr",
                         "exposure", "temp", "holdout_flag2", "holdout_flag3", "groupnum", "lr", "method",
                         "huber_loss", "rmse", "mae", "cdr_score", "ave_score", "neg_ave_score",
                         "exclude_last_diag", "future_dev_periods", ".data", "ul_layer_loss",
                         "cumulative_loss", "cumulative_loss_lag", ":=", "capped_layer_loss",
                         "layer_loss_lag", "agg_layer_loss", "fit_number", "group_num", "min_pct_dev",
                         "max_pct_dev", "weighting", "weibull_atu", "exponential_atu", "inv_power_atu",
                         "weibull_pct_dev", "exponential_pct_dev", "inv_power_pct_dev"))
